version: "1"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
